### ISSUE TITLE
IX compatibility with iS

### ISSUE THREAD

**Issue by srolel** [rwongone/ece356#3]
From the lecture notes:

IS - There is at least one shared lock at a lower level of the tree, but no exclusive locks.

IX - There is least one exclusive lock at a lower level of tree, and there can be shared ones as well.

How can both of these types of locks be granted at the same time on a node?

**Comment by billykeyss** [comment]
From SQL server documentation:

> An intent lock indicates that SQL Server wants to acquire a shared (S) lock or exclusive (X) lock on some of the resources lower down in the hierarchy. For example, a shared intent lock placed at the table level means that a transaction intends on placing shared (S) locks on pages or rows within that table. Setting an intent lock at the table level prevents another transaction from subsequently acquiring an exclusive (X) lock on the table containing that page. Intent locks improve performance because SQL Server examines intent locks only at the table level to determine if a transaction can safely acquire a lock on that table. This removes the requirement to examine every row or page lock on the table to determine if a transaction can lock the entire table.


A node can only be locked if none of it's children are locked. Intent Shared and Intent Exclusive locks on a node does not necessarily imply that the exclusive lock or shared lock has been acquired on a lower hierarchical level thus an IS lock can be overwritten by an IX lock (if no children have been locked)

That is my understanding, I'm not sure why the notes state that there is at least one of those locks at lower levels of the tree. Can a TA clarify this?

**Comment by rwongone** [comment]
Recall that we use the multiple-granularity locking scheme to help our lock manager quickly determine whether a lock should be granted without having to do searches throughout the lock tree.

When we grant an explicit lock on a resource (e.g. database, relation, row), we implicitly grant that lock on all of its children.

Suppose we (explicitly) grant an exclusive lock to one row in some relation. If some transaction wants a shared lock on the entire database now, we ought to be able to deny its request quickly, since one of its children is locked exclusively. This scheme, which uses intent locks, would arrange it such that when we grant the exclusive lock to the row, the relation and database are locked in intent-exclusive (IX) mode, or some other compatible mode.

The multiple-granularity locking protocol is what really decides whether a node can be locked. Mostly, the decision is based on whether the transaction follows 2PL, and whether the node's parent is in a locked in a compatible mode.

Could you give an example of a case where an IS/IX lock is granted on a node, but no S/X lock is granted on any of its descendants? Or perhaps, do you mean this could happen while program is executing, since we cannot grant all of the locks on a path atomically?

**Comment by rwongone** [comment]
And in response to the first question by @Mosho1, I don't see how a node can be locked in two modes at once. Could you clarify what you mean by granting IS and IX at the same time?

**Comment by srolel** [comment]
A transaction requests an IX lock on a node, then another transaction requests an IS lock on the same node. Since they are compatible, the IS lock is granted as well. How does that fit with the definitions of the locks?

There doesn't seem to be a problem conceptually, since IX means a transaction wants to write to some rows, and IS means a transaction wants to read from some cells, so they may not overlap and individual row locks can be used for further locking, but I'm not sure how that fits with the specific definitions I mentioned.

**Comment by rwongone** [comment]
We have a lock compatibility matrix to tell us whether a lock can be granted at a node (see notes, textbook). For a lock to be granted, the requested lock must be compatible with all other locks currently active on the node. Based on this matrix, it should be safe for us to grant IX and IS on the same node.

Imagine a hierarchy where A represents the whole database, with relations B and C as children.

Transaction T1 wants to write and exclusively lock all of B, so it first obtains an IX lock on A (which is allowed, since no locks are currently active on A), then obtains an X lock on B.
Now A is locked in IX mode by T1, and B is locked in X mode by T1.

Transaction T2 wants to read all of C, so it first obtains an IS lock on A (which is allowed, since IS is compatible with IX), then obtains an S lock on C.
Now A is locked in IX mode by T1 and IS mode by T2, B is locked in X mode by T1, and C is locked in S mode by T2.

Suppose we have a third transaction T3, which wants to read something in B, perhaps B1, the first row of B. To do this, it needs an IS lock on A, which is granted, but the IS lock request on B is rejected, since B is already locked in X mode.

It is still true that an IX lock indicates T1's intent to lock a descendant in X or S mode, and an IS lock indicates T2's intent to lock a descendant in S mode only.

I don't think I presented any new information here, but I hope the example helps, @Mosho1 .

**Comment by srolel** [comment]
Yeah, that's a good example and I understand it. But if you look at what I quoted from the lecture notes, it says IS on A means that "There is at least one shared lock at a lower level of the tree, but no exclusive locks", specifically the "no exclusive locks" part. In the example, there is an exclusive lock on B, which is a child of A, contradicting that definition, hence my confusion.

**Comment by rwongone** [comment]
I think that definition would make sense if you restrict it to only the locks that the particular transaction holds, as opposed to locks (belonging to any transaction) held on the node.

If we take that definition to mean locks held globally, then locking to write to a row in B would restrict all other transactions from reading other rows in B, which is probably wrong.

**Comment by srolel** [comment]
I see, yes that would make sense. Thanks!
