### ISSUE TITLE
ARIES example from lecture

### ISSUE THREAD

**Issue by srolel** [rwongone/ece356#5]
![image](https://user-images.githubusercontent.com/5153007/38499666-54d20b9a-3bd6-11e8-8e0a-ad5b2195a9a7.png)

If T1 committed before the checkpoint, why is C in the dirty page table?

**Comment by rwongone** [comment]
I'm checking our textbook now, and it seems that everything I'm reading is consistent with having C removed from the dirty page table when T1 commits, unless somehow we know beforehand that T2 is a transaction that updates both B and C.

When a transaction commits, I don't think we should necessarily remove all of the entries for pages it modified from the DPT, since other transactions could also modify the same pages, but may not have committed those changes. For instance, if T2 updated C prior to T1's commit, we certainly don't want to remove C's entry from the DPT.

In case of system failure, it would be safer to keep the entry until we find a point where no transactions that update that page are active. This gives us a conservative starting point for the recovery, and we know that any LSN before the minimum LSN in the DPT are definitely persisted.

In this example, the only reason I can see (other than a mistake) for keeping C in the DPT is because we have foreknowledge of T2 modifying C, and T2 is still active at the time that T1 commits.

Hopefully you find this helpful, if not confusing.

**Comment by srolel** [comment]
But I think the DPT is only saved (and thus can be retrieved after a crash) at the checkpoint, and at that point there was no knowledge of T2 modifying C.

**Comment by rwongone** [comment]
Yes, I agree with you, but unfortunately I can't think of another reason that would cause the <C, 1> entry to be kept in the DPT.

I think in the case of an exam question, just write your assumptions and you should be fine if they are reasonable.

**Comment by srolel** [comment]
Alright, thanks!
